### 정보단계: x,y변수 선택(숫자 가능)
### 교육단계: data split, model교육시키기, 4개 data를 predict, metrics으로 확인
### 서비스단계: pickle로 만들어 불러오기

In [1]:
from sklearn import datasets

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df= pd.read_excel('./files/advertising.xls')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Daily Time Spent on Site  1000 non-null   float64       
 1   Age                       1000 non-null   int64         
 2   Area Income               1000 non-null   float64       
 3   Daily Internet Usage      1000 non-null   float64       
 4   Ad Topic Line             1000 non-null   object        
 5   City                      1000 non-null   object        
 6   Male                      1000 non-null   int64         
 7   Country                   1000 non-null   object        
 8   Timestamp                 1000 non-null   datetime64[ns]
 9   Clicked on Ad             1000 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 78.2+ KB


숫자 변수 선택
* y: Clicked on Ad
* x: Daily Time Spent on Site, Age, Area Income, Daily Internet Usage, Male

In [4]:
df.shape
# 1000행 10열
df

(1000, 10)

In [5]:
x= df[['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage','Male']]
y= df[['Clicked on Ad']]

In [6]:
x.shape, y.shape
# x변수, y변수 개수 및 데이터 수

((1000, 5), (1000, 1))

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test= train_test_split(x, y)
# 데이터 나누기

In [9]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape
# train은 750개, test는 250개로 나눔

((750, 5), (250, 5), (750, 1), (250, 1))

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
log= LogisticRegression()

In [12]:
log.fit(x_train, y_train)

c:\python\python36\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [13]:
log.coef_, log.intercept_

(array([[-6.34611214e-02,  2.71972507e-01, -1.79438322e-05,
         -2.44972260e-02,  2.34082606e-03]]),
 array([0.00543503]))

In [14]:
log.score(x,y)

0.901

In [15]:
log.score(x_train, y_train)

0.9053333333333333

In [16]:
log.score(x_test, y_test)

0.888

In [17]:
pred= log.predict(x_test)
pred

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [18]:
from sklearn import metrics

In [20]:
print(metrics.classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.86      0.92      0.89       118
           1       0.92      0.86      0.89       132

    accuracy                           0.89       250
   macro avg       0.89      0.89      0.89       250
weighted avg       0.89      0.89      0.89       250



In [21]:
metrics.confusion_matrix(y_test, pred)

array([[108,  10],
       [ 18, 114]], dtype=int64)