In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
x= iris.data
y= iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [5]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y)
# split 순서 지키기 

In [7]:
x_train.shape, x_test.shape, y_train.shape,  y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [8]:
from sklearn.linear_model import LogisticRegression
log= LogisticRegression()

In [9]:
log.fit(x_train, y_train)

LogisticRegression()

In [10]:
log.coef_, log.intercept_

(array([[-0.38969986,  0.87086857, -2.30527959, -0.98610152],
        [ 0.69683225, -0.41736736, -0.20405717, -0.95121247],
        [-0.30713239, -0.45350121,  2.50933676,  1.93731399]]),
 array([  8.93132806,   1.34124873, -10.27257679]))

y = -0.37327011x + 0.89735134x + -2.23115033x + -0.97155103x + 8.46690804

In [11]:
log.predict_proba(x_train[100:104])

array([[3.31887229e-02, 8.91023202e-01, 7.57880754e-02],
       [9.65951941e-05, 1.32949429e-01, 8.66953975e-01],
       [9.52543126e-01, 4.74564497e-02, 4.23938277e-07],
       [9.63383455e-01, 3.66163620e-02, 1.82527652e-07]])

In [12]:
log.predict(x_train[100:104])

array([1, 2, 0, 0])

In [13]:
0.17264465+0.82305126+0.00430409

1.0

In [14]:
from sklearn import metrics

In [15]:
y_pred= log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [16]:
y_pred

array([0, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 0, 2, 2, 1, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 1, 1, 0, 0, 0, 1, 2, 1, 2, 0, 0,
       1, 2, 2, 1, 2, 1, 2, 2, 0, 2, 1, 1, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1,
       2, 1, 1, 2, 2, 1, 0, 1, 2, 2, 0, 2, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0])

In [17]:
y_train

array([0, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 0, 2, 2, 1, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 1, 1, 0, 0, 0, 1, 2, 1, 2, 0, 0,
       1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1,
       1, 1, 1, 2, 2, 1, 0, 1, 2, 2, 0, 2, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0])

In [18]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       1.00      0.95      0.97        39
           2       0.95      1.00      0.97        39

    accuracy                           0.98       112
   macro avg       0.98      0.98      0.98       112
weighted avg       0.98      0.98      0.98       112



In [19]:
metrics.confusion_matrix(y_train, y_pred)
# 대각행렬 (위에서 아래로: 원 데이터, 왼쪽에서 오른쪽으로: predict)

array([[34,  0,  0],
       [ 0, 37,  2],
       [ 0,  0, 39]], dtype=int64)